apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: alertmanager-kube-prometheus-alertmanager
    namespace: monitoring
    files:
      - alertmanager.yaml=config.yaml
    options:
      disableNameSuffixHash: true
