apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/prometheus
  - ../../base/loki
  - ../../base/alertmanager
  - ../../base/ingress

commonLabels:
  environment: prod

patches:
  - path: patches/prometheus-irsa.yaml
  - path: patches/loki-irsa.yaml
  - path: patches/alb-irsa.yaml
  - path: patches/prometheus-resources.yaml
